package Acme::Hello::World::XS;

use strict;
use warnings;

our $VERSION = '0.01;';

require Exporter;
our @ISA    = qw( Exporter );
our @EXPORT = qw( greet    );

use Inline
  VERSION => '0.01',
  NAME    => 'Acme::Hello::World::XS',
  C       => <<'...';
void greet() { printf("Hello, world\n") }
...


# This should prevent M51 warnings from being generated by Inline if a user
# 'require's Acme::Hello::World::XS instead of 'use'.
END {
  Inline->init();
}

1;
